name: bloc_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5

# dependency_overrides:
#   bloc:
#     path: ../../packages/bloc
#   bloc_test:
#     path: ../../packages/bloc_test
#   flutter_bloc:
#     path: ../../packages/flutter_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
